Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 1, in <module>
    import os
TypeError: errorIndicator() missing 2 required positional arguments: 'params' and 'net'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Restarting /scratch/07169/wgl/adjoint/python/Main_no_matrix.py with arguments:
	
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/util.py(55)safe_zip()
-> assert len(arg) == n, f'length mismatch: {list(map(len, args))}'
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 1, in <module>
    import os
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 102, in errorIndicator
    res_u = res_u.at[n].set(residual)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 478, in wrapped
    return f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 525, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 73, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 106, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1117, in broadcast_to
    return util._broadcast_to(array, shape)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 415, in _broadcast_to
    for arr_d, shape_d in safe_zip(arr_shape, shape_tail))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/util.py", line 55, in safe_zip
    assert len(arg) == n, f'length mismatch: {list(map(len, args))}'
AssertionError: length mismatch: [1, 0]
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Breakpoint 1 at /scratch/07169/wgl/adjoint/python/Main_no_matrix.py:102
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(102)errorIndicator()
-> res_u = res_u.at[n].set(residual)
Array([0.], dtype=float32)
Array(0., dtype=float32)
*** AssertionError: length mismatch: [1, 0]
(1,)
()
()
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/util.py(55)safe_zip()
-> assert len(arg) == n, f'length mismatch: {list(map(len, args))}'
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 192, in <module>
    'Refinements': it,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 102, in errorIndicator
    err = jnp.zeros(len(u) - 1)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 478, in wrapped
    return f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/array_methods.py", line 525, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 73, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 106, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1117, in broadcast_to
    return util._broadcast_to(array, shape)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 415, in _broadcast_to
    for arr_d, shape_d in safe_zip(arr_shape, shape_tail))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/util.py", line 55, in safe_zip
    assert len(arg) == n, f'length mismatch: {list(map(len, args))}'
AssertionError: length mismatch: [1, 0]
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(117)lossFn()
-> u = forwardSolve(u_0, dt, params, net)
Traceback (most recent call last):
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 559, in shaped_abstractify
    return _shaped_abstractify_handlers[type(x)](x)
KeyError: <class 'models.ResNetBlock'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 1253, in vmap_f
    out_flat = batching.batch(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 735, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 2258, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 139, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 128, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 771, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 238, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 180, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 311, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 475, in common_infer_params
    in_type = in_avals = tuple(shaped_abstractify(a) for a in explicit_args)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 475, in <genexpr>
    in_type = in_avals = tuple(shaped_abstractify(a) for a in explicit_args)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 561, in shaped_abstractify
    return _shaped_abstractify_slow(x)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 550, in _shaped_abstractify_slow
    raise TypeError(
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Cannot interpret value of type <class 'models.ResNetBlock'> as an abstract array; it does not have a dtype attribute
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
TypeError: Cannot interpret value of type <class 'models.ResNetBlock'> as an abstract array; it does not have a dtype attribute
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(117)lossFn()
-> u = forwardSolve(u_0, dt, params, net)
Traceback (most recent call last):
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 559, in shaped_abstractify
    return _shaped_abstractify_handlers[type(x)](x)
KeyError: <class 'models.ResNetBlock'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 1253, in vmap_f
    out_flat = batching.batch(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 735, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 2258, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 139, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 128, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 771, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 238, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 180, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 311, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 475, in common_infer_params
    in_type = in_avals = tuple(shaped_abstractify(a) for a in explicit_args)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 475, in <genexpr>
    in_type = in_avals = tuple(shaped_abstractify(a) for a in explicit_args)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 561, in shaped_abstractify
    return _shaped_abstractify_slow(x)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api_util.py", line 550, in _shaped_abstractify_slow
    raise TypeError(
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Cannot interpret value of type <class 'models.ResNetBlock'> as an abstract array; it does not have a dtype attribute
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
TypeError: Cannot interpret value of type <class 'models.ResNetBlock'> as an abstract array; it does not have a dtype attribute
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py(4169)_index_to_gather()
-> raise IndexError(msg)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 1253, in vmap_f
    out_flat = batching.batch(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 659, in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 735, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 2258, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 139, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 128, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 771, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 238, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 180, in _python_pjit_helper
    args_flat, _, params, in_tree, out_tree, _ = infer_params_fn(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/api.py", line 311, in infer_params
    return pjit.common_infer_params(pjit_info_args, *args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 480, in common_infer_params
    jaxpr, consts, canonicalized_out_shardings_flat = _pjit_jaxpr(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 918, in _pjit_jaxpr
    jaxpr, final_consts, out_type = _create_pjit_jaxpr(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 322, in memoized_fun
    ans = call(fun, *args)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/pjit.py", line 874, in _create_pjit_jaxpr
    jaxpr, global_out_avals, consts = pe.trace_to_jaxpr_dynamic(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2049, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2066, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 44, in forwardSolve
    u, _ = scan(scanFn,u,jnp.arange(len(dt)))
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 249, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 235, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 60, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 54, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2049, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/interpreters/partial_eval.py", line 2066, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 40, in scanFn
    u_next = forwardFn(u[:l + 1], t[:l + 1], dt[l], params, net)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/core.py", line 676, in __getitem__
    def __getitem__(self, idx): return self.aval._getitem(self, idx)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3908, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3917, in _gather
    indexer = _index_to_gather(shape(arr), idx)  # shared with _scatter_update
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 4169, in _index_to_gather
    raise IndexError(msg)
jax._src.traceback_util.UnfilteredStackTrace: IndexError: Array slice indices must have static start/stop/step to be used with NumPy indexing syntax. Found slice(None, Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=5/0)>, None). To index a statically sized array at a dynamic position, try lax.dynamic_slice/dynamic_update_slice (JAX does not support dynamically sized arrays within JIT compiled functions).
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/opt/apps/intel19/python3/3.9.7/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 183, in <module>
    params, opt_state = trainStep(u_0_train, t, dt, params, net, opt_state,
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 127, in trainStep
    vmap(grad(lossFn, argnums=(3,)),
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 117, in lossFn
    u = forwardSolve(u_0, dt, params, net)
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 44, in forwardSolve
    u, _ = scan(scanFn,u,jnp.arange(len(dt)))
  File "/scratch/07169/wgl/adjoint/python/Main_no_matrix.py", line 40, in scanFn
    u_next = forwardFn(u[:l + 1], t[:l + 1], dt[l], params, net)
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3908, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3917, in _gather
    indexer = _index_to_gather(shape(arr), idx)  # shared with _scatter_update
  File "/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 4169, in _index_to_gather
    raise IndexError(msg)
IndexError: Array slice indices must have static start/stop/step to be used with NumPy indexing syntax. Found slice(None, Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=5/0)>, None). To index a statically sized array at a dynamic position, try lax.dynamic_slice/dynamic_update_slice (JAX does not support dynamically sized arrays within JIT compiled functions).
Post mortem debugger finished. The /scratch/07169/wgl/adjoint/python/Main_no_matrix.py will be restarted
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(1)<module>()
-> import os
> /scratch/07169/wgl/adjoint/python/Main_no_matrix.py(102)errorIndicator()
-> err = jnp.zeros(len(u) - 1)
Deleted breakpoint 1 at /scratch/07169/wgl/adjoint/python/Main_no_matrix.py:102
/work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/plotly/matplotlylib/renderer.py:647: UserWarning:
Looks like the annotation(s) you are trying
to draw lies/lay outside the given figure size.
Therefore, the resulting Plotly figure may not be
large enough to view the full text. To adjust
the size of the figure, use the 'width' and
'height' keys in the Layout object. Alternatively,
use the Margin object to adjust the figure's margins.
Program interrupted. (Use 'cont' to resume).
--Call--
> /work/07169/wgl/ls6/PHO-ICES/adj-env/lib/python3.9/site-packages/jax/_src/tree_util.py(64)tree_unflatten()
-> def tree_unflatten(treedef: PyTreeDef, leaves: Iterable[Leaf]) -> Any: